const GET_ALL_POSTS_LIST_SUCCESS = '[posts]GET_ALL_POSTS_LIST_SUCCESS ';
const GET_ONE_POST_SUCCESS = '[posts]/GET_ONE_POST_SUCCESS';

const FETCH_START = 'FETCH_START';
const FETCH_ERROR = 'FETCH_ERROR';

export default {
  GET_ALL_POSTS_LIST_SUCCESS,
  GET_ONE_POST_SUCCESS,
  FETCH_START,
  FETCH_ERROR,
};
